/*
    grooviks.h
    Generated by FMOD Designer v4.32.2 
*/

#ifndef GROOVIKS_H
#define GROOVIKS_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_GROOVIKS = 1;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_GROOVIKS_UNTITLED = 0;
const int EVENTGROUPCOUNT_GROOVIKS_UNTITLED = 1;
const int EVENT_GROOVIKS_UNTITLED_STONE_GEARS = 0;

/*
    Project-unique event ids
*/
const int EVENTID_GROOVIKS_UNTITLED_STONE_GEARS = 0;

const int EVENTCATEGORY_GROOVIKS_MASTER = 0;
const int EVENTCATEGORYCOUNT_GROOVIKS_MASTER = 1;

const int EVENTCATEGORY_GROOVIKS_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_GROOVIKS_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_GROOVIKS_UNTITLED_STONE_GEARS = "{515117c6-5d02-4ff5-98a7-70ddc6963445}";

/*
    Music cue ids
*/
const unsigned int MUSICCUE_GROOVIKS_NEW_CUE = 3;

#endif /* GROOVIKS_H */
